language: java

jdk:
  - oraclejdk11

install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar

script:
  # Build library and run tests
  - ./gradlew build -x publish -x signArchives -x javadoc