# input directory (path to project)
inputDir: src/test/resources/
# output directory
outputDir: output

# parse Python files with ANTLR parser
parser:
  name: antlr
  languages: [py]

filters:
  - name: by tree size  # exclude the trees that have > 1000 nodes
    maxTreeSize: 1000

# use file names as labels
# this selects the file level granularity
label:
  name: file name

# extract from each tree paths with length 9 and width 2
# save paths in code2vec format
storage:
  name: code2seq
  maxPathLength: 9
  maxPathWidth: 2
