inputDir: 'src/test/resources/methodSplitting/'
outputDir: 'output'

parser:
  type: 'antlr'
  extensions: ['java']

filters:
  - type: 'by function name length'
    maxWordsNumber: 10
  - type: 'by words number'
    maxTokenWordsNumber: 100

problem:
  type: 'function name'

storage:
  type: 'CsvAST'
  format: 'csv'
