type: 'function granularity'

inputDir: 'src/test/resources/methodSplitting/'
outputDir: 'output'

parser:
  type: 'antlr'
  extensions: ['java']

filters:
  - type: 'by function name length'
    maxWordsNumber: 10
  - type: 'by length of any token'
    maxWordsNumber: 100

problem:
  type: 'function name prediction'

storage:
  type: 'ast'
  format: 'csv'
