inputDir: 'src/test/resources/methodSplitting/'
outputDir: 'output'

parser:
  type: 'antlr'
  extensions: ['java', 'js']

filters:
  - type: 'by tree size'
    maxTreeSize: 1000
  - type: 'by words number'
    maxTokenWordsNumber: 1000


problem:
  type: 'file name'

storage:
  type: 'CsvAST'
